inherit_from:
  - .relaxed-rubocop-2.4.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 4.0
  UseCache: true
  DefaultFormatter: progress
  DisplayStyleGuide: true
  DisplayCopNames: true
  Exclude:
    - "external*/**/*"
    - "bazel-*/**/*"
    - "**/examples/**/*"
    - "**/BUILD"
    - "**/*.bazel"
    - "**/*.bzl"
    - "**/rubocop"
    - "**/vendor/bundle/**/*"
  Include:
    - '**/*.rb'
    - '**/*.gemfile'
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/*.ru'
    - '**/Gemfile'
    - '**/Rakefile'

